name: AdvancedAdminHelper
main: at.mcnetwork.lausi.AdvancedAdminHelper
version: 1.1.1
author: LauseggerDevelopment
website: http://McNetwork.at
commands:
  ah:
    usage: /ah
    description: Information about the plugin.
  coords:
    usage: /coords
    description: Information about your position.
  cc:
    usage: /cc
    description: clear the global chat.
    permission: adminhelper.clearchat
  pcc:
    usage: /pcc
    description: clear your private Chat.
    permission: adminhelper.privateclearchat
  globalmute:
    usage: /globalmute
    description: Toggles Globalmute.
    permission: adminhelper.globalmute
  report:
    usage: /report
    description: Reporting a player.
  ram:
    usage: /ram
    description: Shows the RAM Usage.
  team:
    usage: /team
    description: Shows the staff of the server.

permissions:
  adminhelper.*:
    description: Only OP
    children:
      adminhelper.info: true
      adminhelper.reload: true
      adminhelper.clearchat: true
      adminhelper.privateclearchat: true
      adminhelper.report: true
      adminhelper.chat.bypass: true
    default: op
  adminhelper.report:
    description: ALL permissions about reporting
    children:
      adminhelper.report.notification: true
    default: op
  adminhelper.reload:
    description: Reload of the config.yml.
  adminhelper.clearchat:
    description: Clear the global chat.
  adminhelper.privateclearchat:
    description: Clear your private Chat.
  adminhelper.globalmute:
    description: Toggles globalmute.
  adminhelper.globalmute.bypass:
    description: Bypasses the globalmute.
  adminhelper.report.notification:
    description: Get a notification when somebody is reporting a player.
  adminhelper.chat.bypass:
    description: Bypasses Caps and Spam.
  adminhelper.info:
    description: Information about the plugin.
